### ISSUE TITLE
Add embed_subs.py to this package

### ISSUE THREAD

**Issue by pllim** [spacetelescope/wfc3tools#16]
http://www.stsci.edu/hst/wfc3/analysis/grism_obs/wfc3-grism-faq.html#4.3_Answer is "distributing" a script (http://www.stsci.edu/hst/wfc3/analysis/grism_obs/embed_subs.py) that still uses deprecated `pyfits`. It should be officially distributed as part of `wfc3tools` (and also modernized).

**Comment by sosey** [comment]
embedsubs is part of this package as https://github.com/spacetelescope/wfc3tools/blob/master/wfc3tools/embedsub.py

**Comment by pllim** [comment]
xref INC0036630
