### ISSUE TITLE
Can PHTRATIO be 0?

### ISSUE THREAD

**Issue by mcara** [spacetelescope/wfc3tools#20]
I hope this is the correct repository where my issue should be reported.

I have noticed in some WFC3 images that PHTRATION has 0 as value. This does not seem to be correct:

> **SCI,1 = CHIP2:**
 
> PHOTFLAM=        1.9811659E-19 / inverse sensitivity, ergs/cm2/Ang/electron    
  PHTFLAM1=   1.981165900000E-19 / PHOTFLAM on chip 1 when scales are not uniform
  PHTFLAM2=        2.0070588E-19 / PHOTFLAM on chip 2 when scales are not uniform
  PHTRATIO=   1.013069526383E+00 / Ratio of PHTFLAM1/PHTFLAM2                    
 
> **SCI,2 = CHIP1:**
 
> PHOTFLAM=        1.9811659E-19 / inverse sensitivity, ergs/cm2/Ang/electron     
  PHTFLAM1=        1.9811659E-19 / PHOTFLAM on chip 1 when scales are not uniform
  PHTFLAM2=        2.0070588E-19 / PHOTFLAM on chip 2 when scales are not uniform

> **PHTRATIO=0.0** / Ratio of PHTFLAM1/PHTFLAM2                    
 
Obviously PHTRATIO cannot be 0 (unless PHTFLAM2=inf).

**Comment by sosey** [comment]
PHTRATIO is only applied to chip2,  it’s set to zero for chip1 in an effort to warn users that that they shouldn't be applying it themselves. Calibrated data reporting `FLUXCORR=PERFORMED` and `PHOTCORR=PERFORMED` should have non-zero values populated for the other PHT* keywords.  

see also: https://wfc3tools.readthedocs.io/en/latest/wfc3tools/calwf3.html?highlight=fluxcorr

confirmed by @mackjenn
