### ISSUE TITLE
calwf3 no longer able to process IMA files

### ISSUE THREAD

**Issue by npirzkal** [spacetelescope/wfc3tools#60]
WFC3 grism background subtraction relies on being able to process WFC3 IR RAW data using calwf3 first by setting FLATCORR on and CRCORR off. The resulting IMA files data are modified and  are then passed to calwf3 again after setting CRCORR on. This method was recommended to use a few years ago and It used to work perfectly but now calwf3 fails with the error "RuntimeError: wf3ir.e exited with code -6"

**Comment by npirzkal** [comment]
Note that HSTCAL 2.2.0 works fine. 
If you want to test it, just download https://github.com/npirzkal/WFC3_Back_sub, install and run test.py script.

**Comment by mdlpstsci** [comment]
This issue has been fixed in HSTCAL 2.7.2 (August 2021)/WFC3 3.6.2, but it was never tested by Nor.
