### ISSUE TITLE
Version is still listed in docstring for calwf3.py 

### ISSUE THREAD

**Issue by bjkuhn** [spacetelescope/wfc3tools#72]
The parameter `Version` in calwf3.py was removed in [PR #64](https://github.com/spacetelescope/wfc3tools/pull/64)  but the docstring still lists it as a valid parameter.  We need to remove it from the docstring and instead show an example of how to check the calwf3 version (i.e. `!calwf3.e -r` or `!calwf3.e --version`)

**Comment by mdlpstsci** [comment]
See discussion in PR#74.
